### ISSUE TITLE
Error: Cannot find module 'electron-debug'

### ISSUE THREAD

**Issue by abelardolg** [sindresorhus/electron-boilerplate#21]
Hi, 

I run your app on Mac OS X 10.11.6 (15G1004) and this error was showed: 

App threw an error during load
Error: Cannot find module 'electron-debug'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> 
(/hello_electron_boilerplate/index.js:7:1)
    at Object.<anonymous> 
(/hello_electron_boilerplate/index.js:46:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

Kindest regards.

**Comment by kevva** [comment]
Did you run `npm install` before?

**Comment by abelardolg** [comment]
Hello, @kevva It was fixed. 
Thanks for your prompt answer.
Kindest regards.
👍
